"""Changed year_built to int instead of str

Revision ID: 84d6574f9770
Revises: 5b6580bf56a5
Create Date: 2026-02-14 16:58:36.922412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d6574f9770'
down_revision: Union[str, None] = '5b6580bf56a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE properties ALTER COLUMN year_built TYPE INTEGER USING year_built::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE properties ALTER COLUMN year_built TYPE VARCHAR USING year_built::varchar")
    # ### end Alembic commands ###
